Update README.md. Notice about the page link
skills/github-pages pull request #20
Opened 2022-11-02 14:21 UTC by phucnamjose

Add notice about page link for checking. I tried this example and took a while to find where my page is.

### Why:

Closes [issue link]

### What's being changed:

### Check off the following:

- [ ] For workflow changes, I have verified the Actions workflows function as expected.
- [ ] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2022-11-03 04:27 UTC, sinsukehlab requested changes

2022-11-03 04:27 UTC, sinsukehlab commented on README.md
> +  NOTE: Click **Visit site** to see your page.
```suggestion
   > **NOTE**: In the **Pages** of **Settings**, the **Visit site** button will appear at the top. Click the button to see your GitHub Pages site.
```

2022-11-03 09:07 UTC, sinsukehlab approved these changes
Thanks for applying my suggestion.

2023-01-08 11:23 UTC, Migeldavin approved these changes

2023-02-24 17:14 UTC, heiskr commented on README.md
> +   > **NOTE**: In the **Pages** of **Settings**, the **Visit site** button will appear at the top. Click the button to see your GitHub Pages site.
```suggestion
   > **Note**: In the **Pages** of **Settings**, the **Visit site** button will appear at the top. Click the button to see your GitHub Pages site.
```

2023-02-24 17:14 UTC, merged