Update checkout version
skills/github-pages pull request #25
Opened 2023-01-18 22:34 UTC by vps-victor

### Why:

Closes [https://github.com/skills/github-pages/issues/24]

### What's being changed:

The Checkout version of the workflow

### Check off the following:

- [x] For workflow changes, I have verified the Actions workflows function as expected.
- [x] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2023-01-23 16:29 UTC, rsese requested changes
Thank you, just one request to update to `v3` and we should be good!

2023-01-23 16:29 UTC, rsese commented on .github/workflows/0-start.yml
> +        uses: actions/checkout@v3.3.0
```suggestion
        uses: actions/checkout@v3
```

Can you update the changes to ☝️ so we follow the other skills and pin to the major version e.g. https://github.com/skills/continuous-integration/pull/19?

2023-02-05 18:34 UTC, sinsukehlab commented on .github/workflows/1-enable-github-pages.yml
> +        uses: actions/checkout@v3.3.0
The same rule goes.
```suggestion
        uses: actions/checkout@v3
```

2023-02-06 20:21 UTC, vps-victor commented on .github/workflows/5-merge-your-pull-request.yml
> +        uses: actions/checkout@v3.3.0
```suggestion
        uses: actions/checkout@v3
```

2023-02-08 04:07 UTC, sinsukehlab approved these changes

2023-02-14 05:13 UTC, merged