Change git user.name and user.email
skills/github-pages pull request #99
Opened 2024-02-25 23:16 UTC by sinsukehlab

### Summary

Change git user.name and user.email to display github-actions[bot] as a contributor.

### Changes

.github/workflows/0-welcome.yml
- git user.name: github-actions &rarr; github-actions[bot]
- git user.email: github-actions@github.com &rarr; github-actions[bot]@users.noreply.github.com

### Task list

- [x] For workflow changes, I have verified the Actions workflows function as expected.
- [x] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2024-02-26 17:33 UTC, merged

2025-02-05 17:46 UTC, Coste5435 approved these changes

2025-02-06 13:49 UTC, e1b2i3 commented on .github/workflows/0-welcome.yml
> +          git config user.email github-actions[bot]@users.noreply.github.com
Good job

2025-02-08 12:39 UTC, e1b2i3 approved these changes

2025-02-09 18:20 UTC, e1b2i3 commented
🙏

2025-02-09 18:20 UTC, e1b2i3 commented on .github/workflows/0-welcome.yml
> +          git config user.email github-actions[bot]@users.noreply.github.com
🙏

2025-02-09 18:25 UTC, e1b2i3 requested changes

2025-02-09 18:25 UTC, e1b2i3 commented on .github/workflows/0-welcome.yml
> +          git config user.email github-actions[bot]@users.noreply.github.com
Ebrahim1367@sinsukehlab

2025-03-28 02:20 UTC, mtyalkwyt commented
9f8e2ea5c9f681ee75081f9c79ff99fa5707ba5d

2025-05-27 07:08 UTC, Mwipaji reviewed
SkyMan-Ac-Bot

2025-05-27 07:19 UTC, luanxx5 commented
收到



发自我的iPhone


------------------ Original ------------------
From: Mwipaji ***@***.***&gt;
Date: Tue,May 27,2025 3:09 PM
To: skills/github-pages ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [skills/github-pages] Change git user.name and user.email (PR#99)





 
@Mwipaji commented on this pull request.
 
SkyMan-Ac-Bot
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;